def studio_mission(drive_base, module_motor):
    drive_base.straight(60)
    drive_base.turn(-50)
    drive_base.settings(400)
    drive_base.straight(580)
    drive_base.straight(-150)
    drive_base.settings(250)
    drive_base.turn(50)
    drive_base.straight(430)
    drive_base.turn(45)
    drive_base.settings(500)
    drive_base.straight(200)
    drive_base.straight(-200)
    drive_base.turn(-90)
    drive_base.settings(600)
    drive_base.straight(-750)